import { mdsvex } from 'mdsvex';
import tailwindcss from '@tailwindcss/vite';
import adapter from '@sveltejs/adapter-auto';
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import path from 'path';
import fs from 'node:fs';

// import path from 'path';

function generateImageList() {
	return {
		name: 'generate-image-list',

		buildStart() {
			const dir = path.resolve('static/bgs');

			const files = fs
				.readdirSync(dir)
				.filter((file) => /\.(png|jpe?g|webp|gif)$/i.test(file))
				.sort();

			const output = `
/** Generated by vite.config.ts if bgs are not updating restart server */
export const bgImages = ${JSON.stringify(files.map((file) => `bgs/${file}`))};
`;

			fs.writeFileSync(path.resolve('src/lib/generated/images.ts'), output);
		}
	};
}

export default defineConfig({
	plugins: [
		tailwindcss(),
		generateImageList(),
		sveltekit({
			compilerOptions: {
				// Force runes mode for the project, except for libraries. Can be removed in svelte 6.
				runes: ({ filename }) =>
					filename.split(/[/\\]/).includes('node_modules') ? undefined : true,
				experimental: { async: true }
			},

			// adapter-auto only supports some environments, see https://svelte.dev/docs/kit/adapter-auto for a list.
			// If your environment is not supported, or you settled on a specific environment, switch out the adapter.
			// See https://svelte.dev/docs/kit/adapters for more information about adapters.
			adapter: adapter(),
			preprocess: [mdsvex({ extensions: ['.svx', '.md'] })],
			extensions: ['.svelte', '.svx', '.md'],
			experimental: { remoteFunctions: true }
		})
	],
	optimizeDeps: {
		exclude: ['svelte-sonner', '@thisux/sveltednd']
	},
	server: {
		allowedHosts: ['8sybnhrswq.localto.net']
	}
});
